export const STORE_USERID = 'STORE_USERID'
export const STORE_USER_LABEL = 'STORE_USER_LABEL'
export const STORE_NAVIGATION_SCREEN = 'STORE_NAVIGATION_SCREEN'
export const STORE_LABELID = 'STORE_LABELID' 