require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Registration' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'


  target 'RegistrationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Registration-tvOS' do
  # Pods for Registration-tvOS

  target 'Registration-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
